apiVersion: v1
kind: Secret
metadata:
  name: os
type: Opaque
data:
  project_id: 
  user_id: 
  passwd: 
---
apiVersion: v1
kind: Secret
metadata:
  name: watson
type: Opaque
data:
  version: 
  user_id: 
  passwd: 
