apiVersion: v1
kind: Service
metadata:
  name: service-watson-3
  labels:
    app: service-watson-3
spec:
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: deployment-watson-3
  type: NodePort

